services:
  - type: web
    name: otp-server
    env: node
    plan: free
    buildCommand: ""
    startCommand: "node index.js"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      # Configura estos en el dashboard de Render (Settings -> Environment)
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_BASE64
        sync: false
